version: "3"
services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: renvieir/frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: renvieir/backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app